### ISSUE TITLE
Consistency of Simplified Chinese Font 

### ISSUE THREAD

**Issue by sleepymalc** [yuaanlin/pick-time.io#11]
I found out that the font used in the website does not support simplified Chinese well. e.g., 
![image](https://user-images.githubusercontent.com/60427058/183697995-17df3336-00f6-4147-a225-df29c61f9c6c.png)

The word **简**'s font is different from other characters.

**Comment by pan93412** [comment]
Another ugly version:

![CleanShot 2023-09-26 at 22 47 23@2x](https://github.com/yuaanlin/pick-time.io/assets/28441561/8db36331-7d8e-48fd-ac1f-f4cb8f8f1b1f)
