### ISSUE TITLE
bug: calendar date is confusing

### ISSUE THREAD

**Issue by DenChenn** [yuaanlin/pick-time.io#14]
**Desc:**
今天時間是 8/11，明顯已經超過 QQ
但是下方灰色的時間區塊還沒有更新...

**Screenshot:**
<img width="656" alt="Screen Shot 2022-08-11 at 12 54 16 AM" src="https://user-images.githubusercontent.com/42114946/183970655-6b579eeb-f4be-46b9-b34c-fb977fa0112e.png">

**Comment by yuaanlin** [comment]
應該是時區的問題，我改一下你再試試看
